alertmanager:
  enabled: false

grafana:
  adminPassword: ""

prometheus-node-exporter:
  hostRootFsMount:
    enabled: false

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
