apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privileged
spec:
  validationFailureAction: Audit
  validationFailureActionOverrides:
    - action: Enforce
      namespaces:
        - rpg-pipeline
  background: true
  rules:
    - name: check-privileged
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Les conteneurs privilegies et l'escalade de privileges sont interdits (privileged ne doit pas valoir true, allowPrivilegeEscalation: false requis)."
        pattern:
          spec:
            containers:
              - securityContext:
                  =(privileged): "false"
                  allowPrivilegeEscalation: "false"
